server:
  port: 8761

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  server:
#    # 自我保护
#    enable-self-preservation: true
#    # 主动检查服务时间
#    eviction-interval-timer-in-ms: 5000
#    # 服务过期时间，超过这个时间剔除服务
#    #lease-expiration-duration-in-seconds: 10
#    # 服务刷新时间 主动心跳
#    #lease-renewal-interval-in-seconds: 5
#    # 禁用readOnlyCacheMap
#    useReadOnlyResponseCache: false